server:
  port: ${PORT:8081}

#security:
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:9999/uaa/user
spring:
  profiles:
    active: dev
  cache:
    redis:
      time-to-live: 6000
  session:
    store-type: redis

feign:
  hystrix:
    enabled: true

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lieshu.product.mybatis.pojo

---

spring:
  profiles: docker

security:
  oauth2:
    resource:
      userInfoUri: http://security-service:9999/uaa/user
